### ISSUE TITLE
Validator for Sets, NonEmpty

### ISSUE THREAD

**Issue by ysangkok** [flipstone/redcard#13]
It would be useful to assert at Validation-time that a JSON array is not supposed to contain duplicates. This could result in a Set.Set.

There is already a nonEmpty function for asserting that lists are not empty. But why not have this result in a NonEmpty type?

Both of these have ToJSON instances: https://hackage.haskell.org/package/aeson-1.5.6.0/docs/Data-Aeson-Types.html

If you think this is useful, I can take a stab at it.

**Comment by jbrechtel** [comment]
I think they'd both be useful additions. If I had to guess then I'd say there are probably more times I'd use the `NonEmpty` validator than the uniqueness-enforcing `Set` validator but I'd be happy to have both of them available.

**Comment by ysangkok** [comment]
@jbrechtel Submitted a PR for this: #14
